# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WAXYg1KwNFVuEhleK8cryzGnV0Qf4IDV
"""

def identifikasi_hama(g1, g2, g3, g4):
    if g1 and g4:
        return "Hama Wereng"
    elif g2:
        return "Hama Jamur"
    elif g3:
        return "Ulat Daun"
    elif g4 and not g1:
        return "Hama Akar"
    else:
        return "Hama tidak diketahui"

print(identifikasi_hama(True, False, False, True))